Automatically use Obsidian URI scheme for Obsidian vaults
karlicoss/promnesia pull request #270
Opened 2022-02-10 22:19 UTC by Sanqui

Hi,

Obsidian (a PKM app) has a simple URI scheme to access notes inside vaults (dedicated Obsidian directories): https://help.obsidian.md/Advanced+topics/Using+obsidian+URI

I possibly could've bound Obsidian to your `editor://` thing, but I thought it would be a bit cleaner to automatically use the correct URI scheme (or "handler" as you call it) for detected Obsidian vaults (from the `.obsidian` directory).

Sorry for using the dubious `replacer` functionality, but I tried to integrate a URI scheme through `Options` first and it ended up being a bigger mess...  🙂

2022-02-11 10:08 UTC, karlicoss requested changes
Thanks, your change is very welcome! :) 
Hacky, but we can figure out a proper way of handling these later, e.g. it would also be nice for [zotero](https://github.com/karlicoss/promnesia/issues/251) or [logseq](https://github.com/karlicoss/promnesia/issues/192) 

Just one thing, do you think you could add a simple test for this? I don't use obsidian so I won't notice if I manage to break something with refactoring by accident. 
Something similar to [this](https://github.com/karlicoss/promnesia/blob/1b26ccdf9be7c0ac8f8e6e9e4193647450548878/tests/test_auto_indexer.py#L41-L53), and maybe just add a separate directory with small obsidian vault [here](https://github.com/karlicoss/promnesia/tree/master/tests/testdata). Probably best to add a new one instead of changing anything in `auto` dir so you don't have to fix other tests that are using it :)

2022-02-11 10:08 UTC, karlicoss commented on src/promnesia/sources/obsidian.py
> +    if not p.startswith("editor://") or not p.endswith('.md'):
this also needs to handle `Path` (since `PathIsh` can be either `Path` or `str`)

2022-02-11 10:08 UTC, karlicoss commented on src/promnesia/sources/obsidian.py
> +    path = p.split('/', 2)[-1]
best to use something like `Path(*Path(p).parts[1:])` -- this would be more portable, e.g. properly work on Windows

2022-02-12 12:19 UTC, Sanqui commented on src/promnesia/sources/obsidian.py
> +    path = p.split('/', 2)[-1]
the goal of this is to get of the `editor://` prefix, which is system-independent.  I'm assuming on Windows, `p` will be something like `"editor://C:\Documents and Settings\User\file.md"` in which case this is still fine.  I could also do `p[len("editor://"):]`, sadly in Python these tasks always look a bit iffy.

2022-02-12 13:28 UTC, karlicoss commented on src/promnesia/sources/obsidian.py
> +    path = p.split('/', 2)[-1]
aah gotcha! yeah good point, I guess it's okay for now, not sure if `editor://` works on Windows anyway

2022-02-12 14:08 UTC, karlicoss commented
thanks for the test!
actually realized that replacer doesn't take `PathIsh`, should be string instead: `Replacer = Optional[Callable[[str], str]]`
so just can take `: str` and no need to mess with `Path` -- pushed the fix so we don't bounce the PR back and force

For the future if you'll do more PRs, you can check [this guide](https://github.com/karlicoss/promnesia/blob/master/doc/DEVELOPMENT.org#running-tests--mypy-checks) on running mypy locally -- will make it easier to catch issues and contribute :)

2022-02-12 14:08 UTC, karlicoss approved these changes

2022-02-12 14:20 UTC, merged

2022-02-12 16:20 UTC, Sanqui commented
Thanks for merging, and my mistake -- I'll make sure to read the guide in the future.

2022-02-26 03:09 UTC, mdroidian commented
Do you need the `open?path=` on line 7 in obsidian.py?

I couldn't get it to open the file for me without that.

` uri = f"obsidian://open?path={path}"`

2022-03-04 09:50 UTC, karlicoss commented
don't use Obsidian but looks like it? https://help.obsidian.md/Advanced+topics/Using+obsidian+URI#Action+open
@Sanqui can you check if it works for you with `open?path=`? Perhaps you are using an older Obsidian version or something  like that?

2022-06-11 09:57 UTC, Sanqui commented
Sorry for the late reply.  The way it's set up now has been working for me.  This way of accessing files is also documented under [Shorthand formats](https://help.obsidian.md/Advanced+topics/Using+obsidian+URI#Shorthand+formats) in the docs.  I'm using latest Obsidian (v0.14.15) and I'm on Linux.  What is your system @mdroidian?

2022-06-13 17:55 UTC, mdroidian commented
Windows 10, Obsidian v0.14.15

2022-06-13 17:56 UTC, mdroidian commented
> Sorry for the late reply. The way it's set up now has been working for me. This way of accessing files is also documented under [Shorthand formats](https://help.obsidian.md/Advanced+topics/Using+obsidian+URI#Shorthand+formats) in the docs. I'm using latest Obsidian (v0.14.15) and I'm on Linux. What is your system @mdroidian?


Windows 10, Obsidian v0.14.15

2022-10-22 21:23 UTC, karlicoss commented
Sorry, just go back to this. So basically, seems that both formats are supported? 
```
obsidian:///absolute/path/to/my note is equivalent to obsidian://open?path=%2Fabsolute%2Fpath%2Fto%2Fmy%20note
```

I'd imagine the `obsidian://open?path=%2Fabsolute%2Fpath%2Fto%2Fmy%20note` is more reliable in general as it's using the URL encoded format. So IMO it would make sense to Obisidian source to use such URLs by default, should work both on Linux and Windows.